server:
  port: 5555
spring:
  application:
    name: migration-poc

  jpa:
    database-platform: postgres
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres?currentSchema=testdb
    username: postgres
    password: blabla
    #driver-class-name: org.postgresql.Driver
  flyway:
    url: jdbc:postgresql://localhost:5432/postgres?currentSchema=testdb
    user: postgres
    password: blabla
